name: portfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.0.0
  firebase_database: ^11.1.3
  firebase_core: ^3.5.0
  easy_url_launcher: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/author_avatar.png"
  adaptive_icon_background : "#ff5252"
  adaptive_icon_foreground : "assets/images/author_avatar.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

